### PR TITLE
Build man pages from src/vmod_*.vcc files

### PR DESCRIPTION
**Pull request by aondio**
The content of docs/vmod_*.rst has been moved into src/vmod_*.vcc.
During builds vmodtool.py creates, for each vmod present in this
collection, a vmod_*.man.rst based on the corresponding vmod_*.vcc
file.
The docs/ folder contains the generated vmod_*.man.rst files.

### CODE REVIEW

**Comment by Dridi** [comment]
Follow-up for #6 and #8.

**Comment by gquintard** [comment]
Looks good to me.

**Comment by aondio** [comment]
Hi @lkarsten, I'd like to have a feedback on this PR as well.
Thanks

**Comment by lkarsten** [comment]
Works fine for me as well. Good job.

**Comment by lkarsten** [comment]
Never review more than one PR with the same final comment at the time.

Merged the wrong PR. Attempted to use the Revert button, and now everything is messy.

**Pull request merged**
