### PR TITLE
add regular expression filtering to vmod_cookie

### PR DESCRIPTION
**Pull request by nigoroll**
Follow up to #126, basically just squashing and polishing @lkarsten s work

### CODE REVIEW

**Comment by gquintard** [comment]
Ok for me apart from one round of bikeshedding: can we call the functions `.something_regex()` instead of `something_re()`?

**Comment by nigoroll** [comment]
@gquintard sure will adjust

**Comment by nigoroll** [comment]
force-pushed

**Comment by lkarsten** [comment]
-100 on renaming functions one year after the code was written and taken into use.

**Comment by nigoroll** [comment]
@lkarsten I guess a compat-wrapper would be easy.
And I totally understand your frustration as someone who has a varnish-cache PR open which just turned 1 year.

**Comment by nigoroll** [comment]
btw @lkarsten and @gquintard if you can sort this out between each other, I am fine with whatever name. I really only wanted to help get this useful feature merged.

**Comment by gquintard** [comment]
> -100 on renaming functions one year after the code was written and taken into use.

I'd argue that the code never made it to the repo so it should be irrelevant, but since we let it sit for so long, I'll abide.

I'll rename, squash then merge.

**Comment by gquintard** [comment]
I haven't squashed to avoid losing the authors. Thanks to both of you

**Pull request merged**
