### PR TITLE
Add a `cookie.filter` function

### LINKED ISSUE #23: Allowing filtering cookies with a regular expression
`libvmod-cookie` currently has a `filter_except` method which removes all cookies except for those specified by a predefined whitelist. It would be great if there was a `filter` method which could be used to filter cookies matching a specified regular expression. This cannot be done with the current module without iterating over all cookies explicitly with `cookie.delete`.

### PR DESCRIPTION
**Pull request by joshuaspence**
Fixes #23. Adds a `cookie.filter` function which is basically the oppositie of `cookie.filter_except`.

### CODE REVIEW

**Comment by gquintard** [comment]
Looks mostly good, I just have  few remarks:

- please start the new vtc name with 05- instead of 04-
- I'd rather have match_list/mlist than greylist
- is_whitelist should be a VTC_BOOL, and I'd name it "action", with two defines: INCLUDE/EXCLUDE

That's it for the nitpicking. However, is there a real use case for this?

**Comment by joshuaspence** [comment]
Thanks, that's good feedback. `match_list` is a much better name than `greylist` (variables names are always hard).

Yes, there is a real use case for this. We have Varnish configured to strip out a bunch of tracking cookies from all requests. This includes Google Analytics cookies and a few others that I can't remember off the top of my head. We currently strip these cookies out using a regular expression, but a `cookie.filter` function would make our VCL much cleaner.

**Comment by gquintard** [comment]
Very well, that's good to go in then.

I can either pull what you have now and polish myself, or let you have all the glory, as you prefer.

**Comment by joshuaspence** [comment]
Sure, I can finish it off.

**Comment by gquintard** [comment]
Merged, thanks!

**Pull request merged**
