### PR TITLE
updates required for current master

### PR DESCRIPTION
**Pull request by nigoroll**
required to build against current master

### CODE REVIEW

**Comment by Dridi** [comment]
I'll check that this change doesn't break older releases. I expect not, I already performed similar checks for vmod-querystring.

Thanks!

**Comment by Dridi** [comment]
FYI travis ci failed because we are installing Varnish from repo.v-c.org...

**Comment by nigoroll** [comment]
Have pushed more changes
I guess a 5.2 branch before merge would be warranted

**Comment by Dridi** [comment]
@nigoroll we aren't retiring vmod-softpurge, please drop 1e2e8b7. We will keep compiling it for Varnish 4.1, I'll take care of that.

**Comment by nigoroll** [comment]
@Dridi feel free to cherry-pick what you like.
But are you sure keeping a single branch makes sense? My impression is that we've reached a point where we'd just have too much `#ifdef`ery

**Comment by Dridi** [comment]
We had one more change in varnish-trunk regarding `#include` order and rules. We'll revisit this after the 3 months milestone and decide then how we manage compatibility with the different Varnish branches.

https://github.com/varnishcache/varnish-cache/commit/b6921558b9e5ecb431524f9d5dc9aea5af7bd24b

**Comment by nigoroll** [comment]
force-pushed an update to get ahead in the meantime.
the travis-failure is unrelated.

**Comment by Dridi** [comment]
As I said before, we will wait until Dec 15th ABI stabilization to revisit this, but I don't think we need the VSHA256 change:

https://github.com/varnishcache/varnish-cache/commit/8844d6ba3a0ef8e984c6ac70a3acf2cf93f542f2

**Pull request closed without merging**
