### PR TITLE
Man pages generated from *.vcc files

### PR DESCRIPTION
**Pull request by aondio**
I've removed the man/ folder containing all the vmod_*.rst files, vmod_*.vcc are now (well) documented instead.

The doc/ folder is for the generated vmod_*.man.rst files, can be cleaned running make clean.

### CODE REVIEW

**Comment by Dridi** [comment]
@lkarsten is there a reason why we output the man pages in `$(top_builddir)/doc`?

**Comment by aondio** [comment]
@Dridi not sure if you really wanted to tag Lasse or if you wanted to ask me why we use a doc/ folder.
If it is the latter then I can tell you I'm using a doc/ folder for the vmod_*.man.rst because I find very confusing to just have everything in the src folder.

**Comment by lkarsten** [comment]
```
(=2c1ee) lkarsten@IMMER ~/work/varnish-modules> make
make  all-recursive
make[1]: Entering directory '/home/lkarsten/work/varnish-modules'
Making all in src
make[2]: Entering directory '/home/lkarsten/work/varnish-modules/src'
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_cookie_if ../src/vmod_cookie.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_cookie_if ../src/vmod_cookie.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_header_if ../src/vmod_header.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_header_if ../src/vmod_header.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_saintmode_if ../src/vmod_saintmode.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_saintmode_if ../src/vmod_saintmode.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_softpurge_if ../src/vmod_softpurge.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_softpurge_if ../src/vmod_softpurge.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_tcp_if ../src/vmod_tcp.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_tcp_if ../src/vmod_tcp.vcc
WARNING: $Event description is not included in .rst:/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_var_if ../src/vmod_var.vcc

[(9, '')]
WARNING: $Event description is not included in .rst:/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_var_if ../src/vmod_var.vcc

[(9, '')]
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_vsthrottle_if ../src/vmod_vsthrottle.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_vsthrottle_if ../src/vmod_vsthrottle.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_xkey_if ../src/vmod_xkey.vcc
/usr/share/varnish-plus/vmodtool.py -w ../doc/ -o vcc_xkey_if ../src/vmod_xkey.vcc
rst2man ../doc/vmod_cookie.man.rst vmod_cookie.3
rst2man ../doc/vmod_header.man.rst vmod_header.3
rst2man ../doc/vmod_saintmode.man.rst vmod_saintmode.3
make[2]: *** No rule to make target '../doc/vmod_vsthrottle.man.rst', needed by 'vmod_vsthrottle.3'.  Stop.
make[2]: *** Waiting for unfinished jobs....
WARNING: $Event description is not included in .rst:
[(64, '')]
WARNING: $Event description is not included in .rst:WARNING: $Event description is not included in .rst:

[(25, '')]
[(25, '')]
WARNING: $Event description is not included in .rst:
[(64, '')]
make[2]: Leaving directory '/home/lkarsten/work/varnish-modules/src'
Makefile:476: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lkarsten/work/varnish-modules'
Makefile:387: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by lkarsten** [comment]
why both doc/ and docs/?

how should we handle that most people expect the docs to be available on github, but we create the rst files at build/dist time? checking in the resulting files feels wrong, but may be the simplest?

**Comment by lkarsten** [comment]
@Dridi you prefer them at the top level instead? man/ ? Remember that there is a handful of them.

**Comment by Dridi** [comment]
It probably boils down to how I use my editor but usually they don't get in the way. I'd probably prefer a top level man/ to get closer to the varnish source tree.

**Comment by aondio** [comment]
I believe man.rst files should be collected in the man/ folder, while the only hand written doc(which was "non-standard location installation") has been added to the README.
 I'm not able to reproduce Lasse's issue, maybe you managed @Dridi ?

I re-link the branch I'm working on because I believe it gives a better overview instead of this bunch of commits listed here in the PR: https://github.com/aondio/varnish-modules/tree/man_pages

**Comment by Dridi** [comment]
@aondio, I think @lkarsten is referring to the `docs/` (plural) directory in the repository and the `$topdir/doc/` (singular) directory you give to vmodtool.

@lkarsten you can attach files with github releases, maybe a PDF build of the docs would better fit there. With a link to latest docs in the README if github provides such an alias. I perfectly understand the trade-off but I unconditionally lean towards not checking in targets

**Comment by aondio** [comment]
Looking at the branch I'm working on, you'll see there is no more doc or docs directories.
Instead a man/ folder is used the generated man.rst files.

**Comment by Dridi** [comment]
Sorry I didn't comment on the `man/` change but since it was my suggestion I wouldn't disagree so fast with it :)

LGTM, except `src/vmod_'.vcc` in the readme. Did you mean `src/vmod_*.vcc`?

**Comment by aondio** [comment]
Yes, I meant src/vmod_*.vcc, thanks Dridi.

**Comment by lkarsten** [comment]
Reviewed and sent feedback to @aondio offline.

Closing this in anticipation of an updated PR with cleaner commit structure.

**Pull request closed without merging**
