### PR TITLE
Update for current master (76315ee5)

### PR DESCRIPTION
**Pull request by nigoroll**
- xkey needs the EXP_Callback interface which is not currently
  available in master -> made conditional on VARNISH_PLUS
- vtc: replaced semas with barriers
- reflected objcore changes

### CODE REVIEW

**Comment by fgsch** [comment]
master tracks varnish 4.1, not master.

**Comment by nigoroll** [comment]
So can we have a branch which does?

**Comment by fgsch** [comment]
@lkarsten call.

**Comment by lkarsten** [comment]
Discussed with Nils on irc today. We (VS) have limited capacity to keep it continuously updated, and we don't run any production sites on master.

I've pushed an update to the readme file that links to Nils' fork. If it works out in the long run we can consider moving it back in and making the collection more of a community effort.

Closing without merge.

**Comment by nigoroll** [comment]
Thx, updated the README of my fork accordingly

**Pull request closed without merging**
